# Generated by Django 3.0.14 on 2022-03-19 05:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0002_delete_lead'),
    ]

    operations = [
        migrations.CreateModel(
            name='Razze',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_razza', models.CharField(max_length=20)),
                ('desc_razza', models.CharField(max_length=20)),
                ('peso_razza', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Cani',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_cane', models.CharField(max_length=20)),
                ('razza_cane', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='leads.Razze')),
            ],
        ),
    ]
