# Generated by Django 3.0.14 on 2022-03-19 05:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0003_cani_razze'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='cani',
            table='cani',
        ),
    ]
