# Generated by Django 3.0.14 on 2022-03-21 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0004_auto_20220319_0547'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cani',
            name='nome_cane',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
