# Generated by Django 3.0.14 on 2022-03-21 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0005_auto_20220321_1400'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cani',
            name='nome_cane',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
